version: '3'

services:

    database:
        image: mariadb:latest
        env_file: ./build/envfile
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        ports:
            - "$HOST_DB_PORT:3306"
        volumes:
            - ./data:/var/lib/mysql
            #if you insert init data
            #- ../app/initial.sql:/docker-entrypoint-initdb.d/initial.sql
        networks:
            - app

    nginx:
        image: nginx:latest
        # ports:
        #     - "8888:80"
        environment:
            - VIRTUAL_HOST=$VIRTUAL_HOST
        depends_on:
            - app
        volumes:
            - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./build/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
            - ./project:/var/www
            # - ./logs:/var/log/nginx
        networks:
           - external_nginx_proxy
           - app

    app:
        build: build/phpfpm
        image: phpfpm:71
        depends_on:
            - database
        env_file: ./build/envfile
        volumes:
            - ./project:/var/www
        networks:
           - app

#settin virtualhost
networks:
  app:
  external_nginx_proxy:
    external:
        name: proxy_net
